{% set version = '0.4-11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gbrd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gbRd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gbRd/gbRd_{{ version }}.tar.gz
  sha256: 0251f6dd6ca987a74acc4765838b858f1edb08b71dbad9e563669b58783ea91b

build:
  merge_build_host: True  # [win]
  number: 1005
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gbRd')"           # [not win]
    - "\"%R%\" -e \"library('gbRd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gbRd
  license: GPL-2.0-or-later
  summary: Provides utilities for processing Rd objects and files. Extract argument descriptions
    and other parts of the help pages of functions.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: gbRd
# Type: Package
# Title: Utilities for processing Rd objects and files
# Version: 0.4-11
# Date: 2012-01-04
# Author: Georgi N. Boshnakov
# Maintainer: Georgi N. Boshnakov <georgi.boshnakov@manchester.ac.uk>
# Description: Provides utilities for processing Rd objects and files. Extract argument descriptions and other parts of the help pages of functions.
# Depends: tools
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2012-10-01 09:06:44 UTC; mcbssgb2
# Repository: CRAN
# Date/Publication: 2012-10-01 12:27:21
