appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: tznL0aMAiIyRKS4ixmqWw37Hse0YfT5fjI0Kav61XfrIRDY0fLiLA9ZDNEZLb3uThMsWPdOV1Otw+0a7016Ruer8aRA7RMRRCIVaE9yHgzEvQID6z2jMSVSxyA9a367ZKmdnhXy0yyiX/eaSoQubN2GX+nkAEJK+jIyPCxIS8W42uuDYdtBUDIiF86G/sTLF4ZTgtsKwWECYGjFGikeHvY3QuOcBh4fYcvYS8FLMgt6AVZFszTffJOWYb0WGZGBbUyCYTY+Ar61Gr0yFgZWa3ug2CBL02ixEQus854Fq9d9Hyvf1Fx3BpeKjHlTo4QTwPoLhdzccT1qDtcz46Ztd9ik+9hWcT3rR4zp6Ny9KTzz9IVaoY1DppVXpcynbN+mMpRkD8nWO0b1j/F668KtGkU9ozLnkrTxmK/9D8PPaQUvL9SC9f7x4rw5miukq+P0q/5eUfZfi4L8wGSzbjk2vbBCHIiYQD2kegpKUWQn+KOZr1mYD/KYQyxW/nJrevUKGgk7p8+VfUSD/aXVPPSy6rbtKhY18vxlvdaT32MMeq2V4ZnnMcUCPXtQbZ80paLCmEFuBinF/wIh2oIMEY36ZRCQ7nDCppoI/LVe4BrnU5/8BYIsYxyow7pSupTa3QIYknCMvi/Qvf1rkD2I77D+QE5Lhn5980v57iaQ5onB+bX8=}
bot:
  automerge: true
